@IFA @All
Feature: IFA

  Scenario Outline: IFA screenshot "<URL>" UI comparison
    Given a User is browsing NS&I adviser website
    And the User close popup and continue to Adviser Centre
    When the User navigated to the "<URL>" IFA page
    Then the "IFA" page is displayed properly

    Examples:
      | URL                                                                                                      |
      |                                                                                                          |
      | /%C2%A31-million-tax-free-win-two-premium-bonds-holders-kent-and-cumbria                                 |
      | /30-years-premium-bonds-%C2%A31-million-jackpots                                                         |
      | /420-green-savings-bonds-issue-4                                                                         |
      | /500th-premium-bonds-millionaire-made-landmark-draw-jackpot-winners-sefton-and-sheffield                 |
      | /agent-million-gives-two-lucky-premium-bonds-holders-kent-and-york-bank-holiday-weekend-remember         |
      | /agent-million-surprises-first-two-premium-bonds-millionaires-year                                       |
      | /agent-million-visits-london-and-dorset-october                                                          |
      | /annual-report-2017-2018                                                                                 |
      | /april%E2%80%99s-premium-bonds-millionaires-come-somerset-and-croydon                                    |
      | /april-2018-premium-bonds-prizes                                                                         |
      | /aprils-premium-bonds-winners-are-cumbria-and-lothian                                                    |
      | /aprils-premium-bonds-winners-come-hereford-and-worcester-and-west-sussex                                |
      | /assisting-overseas-clients                                                                              |
      | /august%25E2%2580%2599s-premium-bonds-millionaires-come-hereford-worcester-and-essex                     |
      | /august%E2%80%99s-premium-bonds-millionaires-are-devon-and-wales                                         |
      | /august%E2%80%99s-premium-bonds-millionaires-come-hereford-worcester-and-essex                           |
      | /august-2017-premium-bonds-prizes                                                                        |
      | /august-2018-premium-bonds-prizes                                                                        |
      | /augusts-premium-bonds-millionaires-come-dorset-and-buckinghamshire                                      |
      | /autumn-budget-2017                                                                                      |
      | /autumn-budget-2018                                                                                      |
      | /autumn-budget-2024                                                                                      |
      | /autumn-statement-2014-16-things-you-should-know                                                         |
      | /autumn-statement-2016-media-release                                                                     |
      | /autumn-statement-2016-some-things-weve-announced                                                        |
      | /autumn-statement-2022                                                                                   |
      | /autumn-statement-2023                                                                                   |
      | /bank-account-closures-could-affect-your-eu-based-clients                                                |
      | /big-milestone-small-holding-agent-million-visits-400th-premium-bonds-millionaire                        |
      | /boost-savers-nsi-announces-upcoming-interest-rate-increases-across-variable-products                    |
      | /boost-savers-nsi-increases-interest-rates                                                               |
      | /british-savings-bonds-sale-today                                                                        |
      | /budget-2016-key-announcements                                                                           |
      | /budget-announces-nsi-3-year-fixed-rate-bonds-and-new-2024-25-net-financing-target                       |
      | /chancellor-announces-plans-nsi-2015-budget                                                              |
      | /child-millionaire-technological-leap-year-life-premium-bond                                             |
      | /christmas-comes-early-hampshire-isle-wight-and-stockport-decembers-premium-bonds-prize-winners          |
      | /christmas-comes-early-two-premium-bonds-millionaires-scottish-highlands-and-wandsworth                  |
      | /cisi-tv-cash-asset-class                                                                                |
      | /cisi-tv-nsis-revolutionary-new-online-service-financial-planning-firms                                  |
      | /contact                                                                                                 |
      | /coronavirus-help-us-help-you-and-your-clients                                                           |
      | /december-2017-GIB-GGB-return                                                                            |
      | /december-2017-GIB-GGB-return%20                                                                         |
      | /december-2017-premium-bonds-prizes                                                                      |
      | /download-next-wealth-report-fas-and-cash-management                                                     |
      | /early-christmas-bonus-two-premium-bonds-holders-agent-million-shares-news                               |
      | /ernie-brings-delight-devon-and-humberside-february                                                      |
      | /ernie-makes-2022-happiest-new-year-two-new-premium-bonds-millionaires-hertfordshire-and-lancashire      |
      | /ernie-makes-two-millionaires-bristol-premium-bonds-turn-65                                              |
      | /ernie-marches-spring-jackpot-winners-norwich-and-cambridgeshire                                         |
      | /ernie-shares-love-february-jackpot-winners-surrey-and-nottingham                                        |
      | /ernie-shares-love-february-two-new-premium-bonds-millionaires-leeds-and-essex                           |
      | /face-face-events-are-back-and-so-nsi                                                                    |
      | /faqs                                                                                                    |
      | /faqs?page=1                                                                                             |
      | /faqs?page=10                                                                                            |
      | /faqs?page=11                                                                                            |
      | /faqs?page=12                                                                                            |
      | /faqs?page=13                                                                                            |
      | /faqs?page=14                                                                                            |
      | /faqs?page=15                                                                                            |
      | /faqs?page=16                                                                                            |
      | /faqs?page=17                                                                                            |
      | /faqs?page=18                                                                                            |
      | /faqs?page=19                                                                                            |
      | /faqs?page=2                                                                                             |
      | /faqs?page=20                                                                                            |
      | /faqs?page=21                                                                                            |
      | /faqs?page=22                                                                                            |
      | /faqs?page=3                                                                                             |
      | /faqs?page=4                                                                                             |
      | /faqs?page=5                                                                                             |
      | /faqs?page=6                                                                                             |
      | /faqs?page=7                                                                                             |
      | /faqs?page=8                                                                                             |
      | /faqs?page=9                                                                                             |
      | /faulty-nsi-branded-battery-packs                                                                        |
      | /february-2018-premium-bonds-prizes                                                                      |
      | /fireworks-norwich-and-cumbria-ernie-generates-novembers-premium-bonds-prize-winning-numbers             |
      | /good-news-premium-bonds-savers-lower-minimum-investment-and-gifting-facility-be-introduced              |
      | /good-things-come-those-who-wait-julys-premium-bonds-prize-winners                                       |
      | /helping-us-help-you-nsi-branded-statement-requests                                                      |
      | /here-comes-sun-two-new-premium-bonds-millionaires-inner-london-and-surrey                               |
      | /ian-ackerley-appointed-new-nsi-chief-executive                                                          |
      | /investing-behalf-client                                                                                 |
      | /investment-guaranteed-growth-bonds-now-sale                                                             |
      | /invest-premium-bonds-just-%C2%A325                                                                      |
      | /january-2018-premium-bonds-prizes                                                                       |
      | /january-boost-premium-bonds-holders-and-savers-all-ages-nsi-increases-interest-rates                    |
      | /july%E2%80%99s-premium-bonds-millionaires-come-hertfordshire-and-cumbria                                |
      | /july%E2%80%99s-premium-bonds-millionaires-come-staffordshire-and-norfolk                                |
      | /july-2017-premium-bonds-prizes                                                                          |
      | /july-2018-premium-bonds-prizes                                                                          |
      | /julys-premium-bonds-winners-are-county-durham-and-east-riding-yorkshire                                 |
      | /june%E2%80%99s-premium-bonds-millionaires-come-essex-and-south-gloucestershire                          |
      | /june%E2%80%99s-premium-bonds-millionaires-come-southampton-and-surrey                                   |
      | /june-2017-premium-bonds-prizes                                                                          |
      | /june-2018-premium-bonds-prizes                                                                          |
      | /june-delight-new-premium-bonds-millionaires-made-hertfordshire-and-kent                                 |
      | /june-filled-celebrations-ernie-turns-65-winners-essex-and-kirklees                                      |
      | /junes-premium-bonds-winners-come-leicester-and-cleveland                                                |
      | /keeping-you-updated-our-services                                                                        |
      | /lasting-power-attorney-registration-now-digital                                                         |
      | /less-sometimes-more-ernies-premium-bonds-draw                                                           |
      | /major-new-survey-financial-advisers-nsi                                                                 |
      | /managing-premium-bonds-prizes                                                                           |
      | /march-2018-premium-bonds-prizes                                                                         |
      | /marchs-premium-bonds-millionaires-come-nottinghamshire-and-oxfordshire-over-25-billion-prizes-paid      |
      | /maturities                                                                                              |
      | /may-2017-premium-bonds-prizes                                                                           |
      | /may-2018-premium-bonds-prizes                                                                           |
      | /mays-premium-bonds-millionaires-are-greater-manchester-and-wandsworth                                   |
      | /mays-premium-bonds-millionaires-come-derbyshire-and-suffolk                                             |
      | /mays-premium-bonds-millionaires-come-nottingham-and-sefton                                              |
      | /mays-premium-bond-winners-come-surrey-and-wiltshire                                                     |
      | /million-reasons-celebrate-twenties-ernie-picks-first-two-premium-bonds-winners-decade                   |
      | /millions-nsi-customers-benefit-interest-rate-increases-across-variable-products                         |
      | /more-1000-uk-advice-firms-register-use-nsi%E2%80%99s-online-service                                     |
      | /new-green-savings-bonds-issue-295-grossaer                                                              |
      | /new-green-savings-bonds-issue-6                                                                         |
      | /new-interest-rates-selected-nsi-accounts                                                                |
      | /new-issue-green-savings-bonds-570-grossaer                                                              |
      | /new-issue-nsi-green-savings-bonds-launched                                                              |
      | /new-issues-2-and-3-year-british-savings-bonds                                                           |
      | /new-issues-nsi-1-2-3-and-5-year-british-savings-bonds-higher-interest-rates                             |
      | /new-nsi-board-appointments                                                                              |
      | /new-nsi-chief-executive-appointed                                                                       |
      | /new-nsi-green-savings-bonds-sale-today                                                                  |
      | /new-payment-method-nsi%E2%80%99s-online-customers                                                       |
      | /new-rates-premium-bonds-direct-saver-and-income-bonds                                                   |
      | /new-research-nsi-shows-how-financial-planning-landscape-has-changed-over-last-decade                    |
      | /news                                                                                                    |
      | /news?page=1                                                                                             |
      | /news?page=10                                                                                            |
      | /news?page=11                                                                                            |
      | /news?page=12                                                                                            |
      | /news?page=13                                                                                            |
      | /news?page=14                                                                                            |
      | /news?page=15                                                                                            |
      | /news?page=16                                                                                            |
      | /news?page=17                                                                                            |
      | /news?page=18                                                                                            |
      | /news?page=19                                                                                            |
      | /news?page=2                                                                                             |
      | /news?page=20                                                                                            |
      | /news?page=21                                                                                            |
      | /news?page=22                                                                                            |
      | /news?page=23                                                                                            |
      | /news?page=24                                                                                            |
      | /news?page=25                                                                                            |
      | /news?page=26                                                                                            |
      | /news?page=27                                                                                            |
      | /news?page=28                                                                                            |
      | /news?page=29                                                                                            |
      | /news?page=3                                                                                             |
      | /news?page=30                                                                                            |
      | /news?page=31                                                                                            |
      | /news?page=32                                                                                            |
      | /news?page=33                                                                                            |
      | /news?page=34                                                                                            |
      | /news?page=35                                                                                            |
      | /news?page=36                                                                                            |
      | /news?page=37                                                                                            |
      | /news?page=38                                                                                            |
      | /news?page=39                                                                                            |
      | /news?page=4                                                                                             |
      | /news?page=40                                                                                            |
      | /news?page=41                                                                                            |
      | /news?page=42                                                                                            |
      | /news?page=43                                                                                            |
      | /news?page=44                                                                                            |
      | /news?page=45                                                                                            |
      | /news?page=46                                                                                            |
      | /news?page=47                                                                                            |
      | /news?page=48                                                                                            |
      | /news?page=49                                                                                            |
      | /news?page=5                                                                                             |
      | /news?page=50                                                                                            |
      | /news?page=51                                                                                            |
      | /news?page=6                                                                                             |
      | /news?page=7                                                                                             |
      | /news?page=8                                                                                             |
      | /news?page=9                                                                                             |
      | /new-year-celebrations-two-premium-bonds-%C2%A31-million-jackpot-winners-liverpool-and-gloucestershire   |
      | /new-year-joy-two-premium-bonds-millionaires-south-yorkshire-and-wiltshire                               |
      | /new-year-premium-bonds-boost-nsi-increases-rates-across-several-products                                |
      | /new-year-starts-bang-london-and-croydon-ernie-makes-first-two-premium-bonds-millionaires-2019           |
      | /no-tricks-all-treats-premium-bonds-winners-cheshire-and-somerset-november                               |
      | /november%E2%80%99s-premium-bonds-jackpot-winners-come-hertfordshire-and-essex                           |
      | /november-2017-premium-bonds-prizes                                                                      |
      | /novembers-premium-bonds-millionaires-come-west-midlands-and-west-sussex                                 |
      | /nsi-2016-17-annual-results                                                                              |
      | /nsi-2020-21-net-financing-forecast-and-2021-22-net-financing-target                                     |
      | /nsi-2020-21-net-financing-target-revised-%C2%A335-billion-and-nsi-issues-provisional-q1-2020-21-results |
      | /nsi-adviser-survey-reveals-security-and-liquidity-are-driving-behaviour                                 |
      | /nsi-adviser-survey-shows-cash-king-client-conversations                                                 |
      | /nsi-announced-latest-provider-partner-panacea-adviser                                                   |
      | /nsi-announce-new-strategic-partners                                                                     |
      | /nsi-announces-intention-contract-matrix-capital-provide-premium-bonds-jackpot-winner-advisory           |
      | /nsi-announces-new-way-referring-premium-bonds-jackpot-winners-quality-financial-advice-0                |
      | /nsi-announces-rate-changes-some-variable-and-fixed-term-products                                        |
      | /nsi-announces-reduction-interest-rates                                                                  |
      | /nsi-annual-report-2019-20                                                                               |
      | /nsi-annual-report-2020-21                                                                               |
      | /nsi-annual-report-2021-22-customer-service-restored-and-key-financial-targets-met-nsi-announces         |
      | /nsi-annual-report-2022-23-year-delivery-government-and-savers                                           |
      | /nsi-are-going-road                                                                                      |
      | /nsi-boosts-interest-rate-333000-direct-isa-customers                                                    |
      | /nsi-boosts-interest-rates-fixed-term-products                                                           |
      | /nsi-brings-back-one-year-fixed-rate-bonds-general-sale                                                  |
      | /nsi-chief-executive-ian-ackerley-step-down-march-2023                                                   |
      | /nsi-confirm-index-linked-savings-certificates-move-rpi-cpi                                              |
      | /nsi-confirms-award-first-rainbow-strategic-procurement-package-ibm                                      |
      | /nsi-confirms-three-year-contract-extension-atos                                                         |
      | /nsi-delivers-%C2%A321-billion-net-financing-government-q1-2023-24                                       |
      | /nsi-delivers-%C2%A321-billion-net-financing-government-q2-2022-23                                       |
      | /nsi-delivers-%C2%A333-billion-net-financing-government-first-half-2024-25                               |
      | /nsi-delivers-%C2%A377-billion-net-financing-government-q2-2023-24                                       |
      | /nsi-delivers-13-billion-net-financing-government-q1-2022-23                                             |
      | /nsi-enters-testing-phase-its-fa-online-service                                                          |
      | /nsi-extends-contract-matrix-capital-provide-premium-bonds-jackpot-winner-advisory-service               |
      | /nsi-extends-contract-matrix-capital-provide-premium-bonds-jackpot-winner-advisory-service-0             |
      | /nsi-gives-aunts-uncles-and-family-friends-chance-save-young-children                                    |
      | /nsi-gives-valentines-day-boost-savers                                                                   |
      | /nsi-going-road                                                                                          |
      | /nsi-going-road-again-2019                                                                               |
      | /nsi-going-road-autumn                                                                                   |
      | /nsi-going-road-spring                                                                                   |
      | /nsi-going-tour                                                                                          |
      | /nsi-increase-interest-rates                                                                             |
      | /nsi-increase-interest-rates-direct-saver-and-income-bonds                                               |
      | /nsi-increase-premium-bonds-prize-fund-rate                                                              |
      | /nsi-increase-premium-bonds-prize-fund-rate-0                                                            |
      | /nsi-increases-interest-rate-direct-isa-direct-saver-and-income-bonds                                    |
      | /nsi-increases-interest-rate-junior-isa                                                                  |
      | /nsi-increases-interest-rates                                                                            |
      | /nsi-increases-interest-rates-and-issues-provisional-q1-2018-19-results                                  |
      | /nsi-increases-interest-rates-isa-products                                                               |
      | /nsi-introduces-more-ways-whole-family-stay-touch-premium-bonds                                          |
      | /nsi-launches-new-junior-isa                                                                             |
      | /nsi-launches-new-online-service-financial-advice-firms                                                  |
      | /nsi-launches-new-phone-service-financial-advisers                                                       |
      | /nsi-launch-green-savings-bonds                                                                          |
      | /nsi-lifts-trophy-financial-adviser-service-awards-2022                                                  |
      | /nsi-makes-changes-its-fixed-term-product-range-and-issues-provisional-q1-2019-20-results                |
      | /nsi-offers-highest-ever-interest-rate-guaranteed-growth-bonds-and-guaranteed-income-bonds               |
      | /nsi-offers-new-choices-fixed-term-savers                                                                |
      | /nsi-pay-all-premium-bonds-prizes-direct-customers-bank-accounts                                         |
      | /nsi-presents-small-advice-firm-year-money-marketing-awards                                              |
      | /nsi-provisional-q1-2017-18-results                                                                      |
      | /nsi-provisional-q2-2019-20-results                                                                      |
      | /nsi-provisional-q2-2020-21-results                                                                      |
      | /nsi-provisional-q2-2021-22-results                                                                      |
      | /nsi-provisional-q3-2016-17-results-and-2017-18-net-financing-target                                     |
      | /nsi-provisional-q3-2017-18-results-and-2018-19-net-financing-target                                     |
      | /nsi-provisional-q3-2018-19-results-and-2019-20-net-financing-target                                     |
      | /nsi-provisional-q3-2019-20-results-and-2020-21-net-financing-target                                     |
      | /nsi-provisional-q3-2020-21-results                                                                      |
      | /nsi-provisional-q3-2021-22-results-and-2022-23-net-financing-target                                     |
      | /nsi-provisional-q3-2022-23-results-and-2023-24-net-financing-target                                     |
      | /nsi-provisional-q3-2024-25-results-and-2025-26-net-financing-target                                     |
      | /nsi-reduce-interest-rates-24-november-2020                                                              |
      | /nsi-reduces-interest-rate-direct-isa                                                                    |
      | /nsi-reduces-interest-rate-new-customers-purchasing-3-year-guaranteed-growth-bonds-and-guaranteed        |
      | /nsi-reduces-interest-rates                                                                              |
      | /nsi-reduces-interest-rates-offered-variable-rate-products                                               |
      | /nsi-reduces-interest-rates-some-fixed-term-products                                                     |
      | /nsi-releases-archive-imagery-celebrate-65th-anniversary-first-premium-bonds-draw                        |
      | /nsi-releases-new-green-savings-bonds-issue-today                                                        |
      | /nsi-releases-new-issues-guaranteed-growth-bonds-and-guaranteed-income-bonds-reduced-purchase-limits     |
      | /nsis-one-year-guaranteed-growth-bonds-and-guaranteed-income-bonds-withdrawn-general-sale                |
      | /nsi-sponsoring-personal-finance-awards-2016                                                             |
      | /nsi-sponsoring-personal-finance-awards-2017                                                             |
      | /nsi-sponsoring-personal-finance-awards-2018                                                             |
      | /nsi-supports-savers-unprecedented-time                                                                  |
      | /nsi-survey-reveals-most-financial-advisers-are-willing-advise-portfolios-%C2%A350000-or-under           |
      | /nsi-survey-reveals-outlook-cash-becoming-brighter-among-financial-advisers                              |
      | /nsi-survey-shows-confidence-advice-industry-all-time-high                                               |
      | /nsi-will-delay-phasing-out-premium-bonds-prize-warrants-until-spring-2021                               |
      | /obtaining-client-information                                                                            |
      | /october%E2%80%99s-premium-bonds-draw-crowns-two-new-millionaires-derbyshire-and-gloucestershire         |
      | /october%E2%80%99s-premium-bonds-millionaires-come-greater-manchester-and-west-scotland                  |
      | /october%E2%80%99s-premium-bonds-millionaires-come-outer-london-and-suffolk                              |
      | /october-2017-premium-bonds-prizes                                                                       |
      | /please-vote-nsi-financial-adviser-service-awards-2019                                                   |
      | /please-vote-nsi-financial-adviser-service-awards-2020                                                   |
      | /powers-attorney                                                                                         |
      | /premium-bonds-%C2%A31-million-jackpot-double-celebration-yorkshire                                      |
      | /premium-bonds-%E2%80%93-2024-year-figures                                                               |
      | /premium-bonds-millionaires-are-made-hertfordshire-and-cheshire-west-and-chester                         |
      | /premium-bonds-prize-fund-rate-reduced-march-2024-draw                                                   |
      | /premium-bonds-take-quantum-leap-new-random-number-generator-ernie-5-picks-two-new-jackpot-winners       |
      | /premium-bonds-winners-bristol-and-kent-march-2021-draw                                                  |
      | /premium-bonds-winners-cumbria-and-outer-london                                                          |
      | /premium-bonds-winners-hertfordshire-and-essex                                                           |
      | /premium-bonds-winners-inner-london-and-gloucestershire                                                  |
      | /premium-bonds-winners-inner-london-and-north-yorkshire                                                  |
      | /premium-bonds-winners-manchester-and-south-gloucestershire-december-2020-draw                           |
      | /premium-bonds-winners-nottingham-and-stoke-trent                                                        |
      | /premium-bonds-winners-tyne-and-wear-and-surrey                                                          |
      | /premium-bonds-winners-wales-and-south-scotland                                                          |
      | /premium-bonds-winners-west-scotland-and-barnet-first-draw-2021                                          |
      | /premium-bonds-year-figures                                                                              |
      | /premium-bond-winners-devon-and-west-sussex-november-2020-draw                                           |
      | /privacy-notice                                                                                          |
      | /provisional-q1-2021-22-results                                                                          |
      | /resources                                                                                               |
      | /resources?page=1                                                                                        |
      | /resources?page=10                                                                                       |
      | /resources?page=11                                                                                       |
      | /resources?page=12                                                                                       |
      | /resources?page=13                                                                                       |
      | /resources?page=14                                                                                       |
      | /resources?page=15                                                                                       |
      | /resources?page=16                                                                                       |
      | /resources?page=17                                                                                       |
      | /resources?page=2                                                                                        |
      | /resources?page=3                                                                                        |
      | /resources?page=4                                                                                        |
      | /resources?page=5                                                                                        |
      | /resources?page=6                                                                                        |
      | /resources?page=7                                                                                        |
      | /resources?page=8                                                                                        |
      | /resources?page=9                                                                                        |
      | /revised-nsi-net-financing-target-2018-19-and-provisional-q2-2018-19-results                             |
      | /savers-be-able-access-%C2%A31500-tax-free-pension-advice                                                |
      | /security-no1-priority-say-financial-advisers                                                            |
      | /september-2017-premium-bonds-prizes                                                                     |
      | /september-2018-premium-bonds-prizes                                                                     |
      | /septembers-premium-bonds-millionaires-are-shropshire-and-bristol                                        |
      | /september-starts-two-new-premium-bonds-jackpot-winners-sefton-and-west-sussex                           |
      | /september-surprise-surrey-and-hertfordshire-celebrate-newly-crowned-premium-bonds-millionaires          |
      | /sipps-and-ssass                                                                                         |
      | /site-conditions-and-legal                                                                               |
      | /sites/nsandi-adviser/files/asset/forms/guaranteed-growth-bonds-application-form.pdf                     |
      | /sites/nsandi-adviser/files/asset/forms/guaranteed-income-bonds-application-form.pdf                     |
      | /spring-budget-2017                                                                                      |
      | /spring-budget-2020                                                                                      |
      | /spring-budget-2021                                                                                      |
      | /spring-budget-2024                                                                                      |
      | /spring-statement-2019                                                                                   |
      | /spring-statement-2022                                                                                   |
      | /spring-statement-2025                                                                                   |
      | /spring-time-celebrations-premium-bond-holders-devon-and-outer-london                                    |
      | /summer-boost-savers-nsi-increases-premium-bonds-prize-fund-rate-and-junior-isa-interest-rate            |
      | /summer-budget-2015-key-announcements                                                                    |
      | /sun-out-and-so-nsi-year                                                                                 |
      | /supporting-premium-bonds-jackpot-winners                                                                |
      | /supporting-you-and-your-clients                                                                         |
      | /tender-premium-bonds-advisory-service-launched                                                          |
      | /tracing-lost-savings                                                                                    |
      | /treats-not-tricks-october%E2%80%99s-premium-bond-jackpot-winners-dorset-and-essex                       |
      | /trusts                                                                                                  |
      | /two-premium-bonds-holders-dorset-and-wandsworth-hit-%C2%A31-million-jackpot                             |
      | /two-premium-bonds-holders-hampshire-and-outer-london-celebrate-their-big-win-%C2%A31-million            |
      | /two-premium-bonds-holders-outer-london-and-devon-celebrate-their-%C2%A31-million-big-win                |
      | /two-premium-bonds-holders-warwickshire-and-cornwall-celebrate-%C2%A31-million-jackpot-win               |
      | /two-premium-bonds-holders-west-sussex-and-hampshire-celebrate-%C2%A31-million-jackpot-win               |
      | /two-premium-bonds-holders-west-sussex-and-manchester-celebrate-%C2%A31-million-jackpot-win              |
      | /uk-green-financing-%E2%80%93-allocation-report-2023                                                     |
      | /uk-green-financing-%E2%80%93-allocation-report-2024                                                     |
      | /uk-green-financing-allocation-report                                                                    |
      | /videos                                                                                                  |
      | /welcome-new-adviser-centre                                                                              |
      | /we-want-hear-you                                                                                        |
      | /what-do-when-client-dies                                                                                |
      | /why-nsandi                                                                                              |

